//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public int AccountNumber { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public Nullable<double> AccountBalance { get; set; }
    }
}
