//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int Id { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string Fullname { get; set; }
        public Nullable<double> TransferAmount { get; set; }
        public Nullable<int> TransferTo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
